- name: play example #1
  hosts: web,db
  vars:
   filetext: happy new year
  tasks:
  - name: #1 manage presh user
    user: 
     name: presh
     uid: 5000
     state: present
  - name: #2 install nginx
    apt: 
     name: nginx
     state: present
  - name: #3 file management
    copy:
     dest: /tmp/example2-file-1
     content: "{{ filetext }}"
  - name: #4 file management
    copy:
     dest: /tmp/example2-file-2
     content: "{{ filetext }}"
  - name: #5 file management
    copy: 
     dest: /tmp/example2-file-3
     content: "{{ filetext }}"
  - name: #6 file management
    copy: 
     dest: /tmp/example2-file-4
     content: "{{ filetext }}"

